### ISSUE TITLE
mismatched tag in parser

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#35] opened 2015-05-02 01:44 UTC
uncle wileymorgan$ runtests.py trunk/ -stag ~/Documents/research/uncle/staging/ -rerun "findClusters"
ERROR: parsing executable dependency call get_spaceGroup_atomTypes
	(if (digit1==digit2 )
</doc>tion "make_primitive" in this same module.e to a primitive one, use theye**
</doc>mary>orresponding fractional translations. of the space group and compute
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/runtests.py", line 91, in <module>
    initialize()
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/runtests.py", line 39, in initialize
    t.writeall(args["codedir"])
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/tester.py", line 499, in writeall
    self.parser.parse(filepath, True, True)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 305, in parse
    self._parse_dependencies(pmodules, dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 118, in _parse_dependencies
    self.load_dependency(base, dependencies and recursive, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 319, in load_dependency
    self.parse(self._pathfiles[fkey], dependencies, recursive)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 305, in parse
    self._parse_dependencies(pmodules, dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 118, in _parse_dependencies
    self.load_dependency(base, dependencies and recursive, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 319, in load_dependency
    self.parse(self._pathfiles[fkey], dependencies, recursive)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 305, in parse
    self._parse_dependencies(pmodules, dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 118, in _parse_dependencies
    self.load_dependency(base, dependencies and recursive, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 319, in load_dependency
    self.parse(self._pathfiles[fkey], dependencies, recursive)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 305, in parse
    self._parse_dependencies(pmodules, dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 118, in _parse_dependencies
    self.load_dependency(base, dependencies and recursive, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 319, in load_dependency
    self.parse(self._pathfiles[fkey], dependencies, recursive)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 305, in parse
    self._parse_dependencies(pmodules, dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 118, in _parse_dependencies
    self.load_dependency(base, dependencies and recursive, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 319, in load_dependency
    self.parse(self._pathfiles[fkey], dependencies, recursive)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 305, in parse
    self._parse_dependencies(pmodules, dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 118, in _parse_dependencies
    self.load_dependency(base, dependencies and recursive, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 319, in load_dependency
    self.parse(self._pathfiles[fkey], dependencies, recursive)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 284, in parse
    dependencies, recursive, greedy)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 159, in _parse_from_file
    self._parse_docstrings(filepath)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/code.py", line 126, in _parse_docstrings
    self.modulep.docparser.parsexml(xmlstring, self.modules)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/parsers/docstring.py", line 291, in parsexml
    xmlroot = ET.fromstring(xmlstring)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 94, column 3

**Comment by rosenbrockc** [comment] 2015-05-04 15:36
Added more useful error message in Revision 1.5.6; the error is caused by badly formed XML and needs to be fixed by the user. The new error will show the excerpt of badly formed XML that is causing the problem so that it can be fixed (instead of just passing a line and column number, but no other information).

**Closed by rosenbrockc** 2015-05-04 15:36 UTC
